apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: todo-management-spring-boot  # Updated label
  name: todo-management-spring-boot  # Updated name
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-management-spring-boot  # Updated label
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/custom-network: "true"
        io.kompose.service: todo-management-spring-boot  # Updated label
    spec:
      containers:
        - image: todo-management-spring-boot:${BUILD_NUMBER}  # Updated image with build number
          name: todo-management-spring-boot  # Updated container name for consistency
          ports:
            - containerPort: 8780
              protocol: TCP
          resources: {}  # Resource requests and limits can be specified here if needed
      restartPolicy: Always
