apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: todo-management-for-mavenrepo
  name: todo-management-for-mavenrepo
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8780
      targetPort: 8780
      nodePort: 30001  # Optional: specify a NodePort for external access
  selector:
    io.kompose.service: todo-management-for-mavenrepo
status:
  loadBalancer: {}
