version: "3"

services:

  app:
    build:
      context: "./"
      dockerfile: Dockerfile
    container_name: 'DB-Application'


    ports:
      - '8780:8780'
    networks:
      - my-proxy-net
networks:
  my-proxy-net:
    external:
      name: custom_network